dev_Petrov_03
grom4er/spring_intro pull request #3
Opened 2021-02-10 13:35 UTC by grom4er

2021-02-10 13:40 UTC, Resci approved these changes

2021-02-10 15:48 UTC, dmytro-hryhoruk requested changes

2021-02-10 15:48 UTC, dmytro-hryhoruk commented on src/main/java/dao/impl/UserDaoImpl.java
> +            return Optional.ofNullable(user);
let's do this inline

2021-02-10 15:48 UTC, dmytro-hryhoruk commented on src/main/java/dto/UserResponseDto.java
> +
```suggestion
```

2021-02-10 15:48 UTC, dmytro-hryhoruk commented on src/main/java/service/UserMapper.java
> +
```suggestion
```

2021-02-10 15:48 UTC, dmytro-hryhoruk commented on src/main/java/service/impl/UserServiceImpl.java
> +        return userDao.getById(id).get();
you are requesting db twice

2021-02-11 08:24 UTC, dmytro-hryhoruk requested changes

2021-02-11 08:24 UTC, dmytro-hryhoruk commented on src/main/java/controller/UserController.java
> +    @GetMapping("/getAll")
```suggestion
    @GetMapping
```

2021-02-11 08:24 UTC, dmytro-hryhoruk commented on src/main/java/service/impl/UserMapperImpl.java
> +    }
we don't need this method now

2021-02-11 08:24 UTC, dmytro-hryhoruk commented on src/main/java/dto/UserResponseDto.java
> +    private String name;
let's add id too

2021-02-11 08:24 UTC, dmytro-hryhoruk commented on src/main/java/service/impl/UserServiceImpl.java
> +        return user.get();
return userDao.getById(id).orElse(null);

2021-02-11 08:31 UTC, dmytro-hryhoruk commented on src/main/java/service/impl/UserServiceImpl.java
> +        return user.get();
but let's use orElseThrow() instead; It's better to throw exceptions in such cases. Later we will learn how our controller can handle such situations

2021-02-11 11:41 UTC, dmytro-hryhoruk approved these changes

2021-02-11 11:53 UTC, merged